sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mrlnvndn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrlnvndn/docker-react npm run test